version: '3'

services:
  inventory_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  orders_db:
    container_name: orders_db
    image: mysql:8
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: orders
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    ports:
        - "3306:3306"
    expose:
        - 3306

  product_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432

  keycloak_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - keycloak_db
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak_db
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_PORT: 5433
        KC_HTTP_PORT: 8181

