version: '3'

services:
  inventory_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  orders_db:
    container_name: orders_db
    image: mysql:8
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: orders
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
    ports:
        - "3306:3306"
    expose:
        - 3306

  product_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432

  keycloak_db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - keycloak_db
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak_db
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_PORT: 5433
        KC_HTTP_PORT: 8181

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
        - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.24.2
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    ports:
      - "9090:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    restart: unless-stopped
    extra_hosts:
        - "host.docker.internal:host-gateway"
    links:
      - prometheus
    volumes:
        - ./files/grafana:/var/lib/grafana
    environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
        - prometheus



